import { useState } from 'react'
import './DLP1.css'

function DLP1() {

    return (
        <>
        <div id="dlp1-all">
            <h1>Predicting Market Values of Premier League Players <a href="https://github.com/A-Merino/Premier-League-Stats/blob/main/DLProj1.ipynb">(github)</a></h1>
            <h2>Backgroud</h2>
            <p>The Premier League is England's top soccer/football league and is internationally watched and loved. This is true because it is one of, if not the best, leagues in the world. And to reach that status, the games need to be entertaining, and for the games to be entertaining, you need the best players in the world on every team. So long story short (or long correlation short), the players playing in the Premier League, make the league great, which intuitively makes sense, but going through the process allows us to get into the context of where our problem lies.</p>
            <p>In the Premier League, and soccer leagues everywhere, the main way to get a new player is to buy that player from another team or wait for the player to finish their contract and pick them up for free. The amount of money a team pays to buy another team’s player is called a <strong>transfer value</strong>, since that numerical value is how much the team paid for the transfer of the player. That transfer value is essentially an agreed upon term between the buying and selling team for how much that player is worth. Now keeping that in mind…</p>
            <p>A <strong>market value</strong> for a player is the value that player would be worth if the player market was a free market. And a free market is an economic term which means that the price of something is determined by the supply and demand of buyers and sellers without any intervention. The definition of a market value does sound similar to transfer values, but with transfer values there are soccer federation standards that must be upheld with the spending and acquiring of money. The market value of a player and the potential transfer value of the player, more times than not will be different. The transfer value, however, is highly affected by the market value.</p>
            <p>Now that we know what a market value is, we should look into how a market value is created. I collected the market value data from the website <a href="https://www.transfermarkt.com">TransferMarkt</a>. TransferMarkt is the most widely recognized and accepted group which creates market values. The process of creating a market value is just as scientific as fine tuning a neural network (which is not every scientific at all). The market values are created by the soccer community, with a group consensus, not by any mathematical models or anything of the sort. Which does make the integrity of the data seem weak because this can introduce biases to the values.</p>

            <p>According to the TransferMarkt website, these are the most important factors to a player's market value:</p>
            <ul>
                <li>Future prospects</li>
                <li>Age</li>
                <li>Performance at the club and national team</li>
                <li>Level and status of the league, both in sporting and financial terms</li>
                <li>Reputation/prestige</li>
                <li>Development potential</li>
                <li>League-specific features</li>
                <li>Marketing value</li>
                <li>Number & reputation of interested clubs</li>
                <li>Performance potential</li>
                <li>Experience level</li>
                <li>Injury susceptibility</li>
                <li>Different financial conditions of clubs and leagues</li>
                <li>General demand and "trends" on the market</li>
                <li>General development of transfer fees</li>
                <li>External factors such as the coronavirus pandemic and its consequences</li>
            </ul>

            <p>Many of these values however are not numerical or categorical, but based on opinions/biases. Reputation, future prospects, marketing value (commercials), injury susceptibility, development potential. None of these (other than injury susceptibility) affect how a player will play throughout a season. Yes, they could improve throughout the season, but that will reflect in the stats of the player. This brings us to the crux of the problem…</p>

            <h3 className="red">Market Values are inherently biased.</h3>

            <p>Now how should we git rid of these biases?</p>
            <p>My solution is to give the statistics of all the players in the league to a neural network and let it crunch the numbers.</p>
            <h2>What is a Neural Network?</h2>
            <p>Neural Networks are a form of machine learning, AI, whatever you like to call it. All of these ideas, when boiled, down are essentially really complicated mathematical models. These models take in a bunch of numerical inputs and give one or more numerical outputs. Everything inbetween is just a bunch of matrix multiplication and other fun mathematical operations that computers are really good at.</p>
            <p>A really simple example would be the equation of a line, where we have an input, x, and an output, y. For every x-value you have, you can receive a y-value, and using that you can plot a line. This is the idea of Linear Regression, which is a machine learning technique that is extremely naive but simple to understand. A neural network is a bit more complicated, but we still have an input, which is now a vector, and an output.</p>
            <p>That's all I really feel comfortable explaining about neural networks before I say something silly that doesn't make sense, so <a href="https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi">here are good videos on what neural networks fully are</a>.</p>

            <h2>Data</h2>
            <p>For the data, I am using the full season statistics of players in the Premier League from the 2017/18 season to the 2023/24 season. Each player has a minimum of 113 unique statistics from the season. Goalkeepers, however, have 140 statistics since they have a lot more unique statistics that are tracked, which all other positions do not have. The statistics include goals, minutes played, passes, expected goals, throw ins, essentially every numerical statistic that exists.</p>
            <p><strong>The output we are trying to predict is their expected market value based on the statistics from one season</strong>, which will be in millions of Euros. (10 = 10 million Euros)</p>
            <p>The data will be split into train, validation, and test sets, with 5 seasons (2017/18 – 2021/22) going into train, 2022/23 will consist of validation, and 2023/24 will be the test set.</p>
            <p>Earlier, I mentioned that the market values were biased, and the goal was to strip away those biases from the value. But I am training my neural networks on these biased values. Here I will excuse the biases and trust that the community did a well enough job to properly evaluate the players, which does seem like the case more times than not. This is also why my training data is also the oldest seasons, so that the models are not affected by the most recent biased values. We want to keep the most recent season unknown to the model so we can see in current time, which players are being under/over valued based on their market value.</p>
            <p>The Forwards, Midfielders, and Defenders datasets will have 113 inputs, while the Goalkeepers and Full dataset will have 140 inputs. In the full dataset, the forwards, midfielders, and defenders will be zero padded to fit 140 input features.</p>

            <h2>Experimentation (Overview)</h2>
            <p>All of my code and training was done in a jupyter notebook, which can be viewed <a href="https://github.com/A-Merino/Premier-League-Stats/blob/main/DLProj1.ipynb">here</a>. The type of neural network used was a Feed-Forward Neural Network that had 10 layers and used the Adamax optimizer. However, there were four different weights for the neural network shape because after a few trials, I realized that the models perform better when players are separated by position. This allowed for more accurate results, but what makes a result accurate in this problem?</p>
            <p>For the model to be accurate, it should be close to the given market value of the player. So I set up three ranges, one for predicitons within 1% of the range of dataset outputs, one within 5%, and one within 10%. The range of given market values were from 0.25 to 180 million euros.</p>
            
            <h2>Analysis</h2>

            <h3 className="green">Positive Difference Players</h3>

            <p>The models predicted that these 9 players' market values were 25 million euros or more than the market values they were given. For all of these players, it was because they had an amazing 23/24 season, which the models correctly identified</p>

            <h4>Pascal Groß</h4>
            <p>Pascal Groß had a very good season, ending with 4 goals and 10 assists. He was 4th in the league in Shot-Creating Actions (SCAs) which tracks passes, tackles, etc. that lead to his team taking a shot on the opponent's goal, and 19th in Goal-Creating Actions (GCAs), which is the same statistic, only if the shot scored a goal (which is mainly up to his teammates). He ranked 3rd highest in the league (2nd highest midfielder) in passes completed and tied 3rd for the most assists in the season as well. Another very important statistic was key passes, passes that lead to a shot, and he was second in the league, as well as 2nd for passes into the opponent's third of the field as well.</p>
            <p>There are a few more passing statistics where he was top 3 in the league. All of this is showing that he was an integral central midfielder for his team throughout the season. He was given a market value of 8 million, mainly because he is 32 years old. For most soccer players, their prime is normally in the ages of 26-28. Groß being 32 is past his prime, and teams do not want to pick up players that are past their prime because they only have a few playing seasons left, and are more likely to have injuries.</p>
            <p>Over the summer he was sold for 7 million euros to a German team (his home country) and is playing decently well, but there is not enough data to tell whether or not he is having a good season.</p>

            <h4>Thiago Silva</h4>
            <p>Thiago Silva has been in professional soccer leagues since 2003 (before I was even born), which is a testament to how long he has played the game. In the 23/24 season he was 38 years old, which is very much past the prime of normal players, but defenders normally do play longer than forwards or midfielders because they run a significant amount less throughout a game on average. But he is nearing the end of his career and because of that, his market value is 1 million euros. However the model predicted him at 32 million euros, which is an extremely large difference.</p>
            <p>He was in the top 10 for times clearing the ball out of the box but also tied for 6th in most errors leading to a goal. For passing he was 10th in total completed passes, bit first in passing percentage (completed passes / passes attempted) with a whopping 94%. He had the 16th most touches on the ball throughout the season, but was only dispossed once, which is the second best for any non-goalkeeper that had over 500 touches on the ball. He did have three goals, which is very good for a defender, but other than that his stats were near the middle of the league.</p>
            <p>He was most likely given a 32 million euro price tag by the model because over all he had a season that was similar to what a 32 million euro player had in the training dataset.</p>
            
            <h4>James Maddison</h4>
            <p>James Maddison, 26 during the 23/24 season, played a season worth a 110 million euro player, while he had a 70 million euro market value. It was his first season at a new team, which got him for 46 million euros, which was, in retrospect, one of the best deals of the summer. (Note that the team he came from got relegated {"{dropped from the league}"} so he had a slightly discounted transfer value because of that.) To get a top player, which has performed well season after season, that is coming into his prime years was extremely smart by the team which got him. And he is already paying off.</p>
            <p>He was tied 12th for most assists (9), 7th in SCA (161), and 2nd highest in SCA per 90 minutes played. He played just under 24 complete games in a 38 game season, and if he had played only 10 more games (the same amount as the player in first in this category) at the same rate per 90 minute game he would have the most in the league. He tied 10th for GCAs, and 8th in progressive passes (passes forward essentialy). Ranking high in all of these statistics as a midfielder is very good for your market value, and the model seems to agree with that as well.</p>
            
            <h4>Others</h4>
            <p>Jeremy Doku and Simon Adingra are two young players who had a breakout season in 23/24. Their values were predicted similarly to James Maddison's. The models predicted them to be worth 39 million and 27.5 million more respectively. This was Jeremy Doku's first Premier League season as he was bought for 60 million euros (when his market value was 24 million) and he immediately proved to be a great player. he was first in dribbles forward into the opponent's box, and 7th in receiving passes in advanced positons. Simon Adingra also played his first season in the Premier League as well and he played brilliantly (actually one of my favorite players to watch) and the model agrees. He is very good at dribbling the ball forward and recieving passes in forward positoins, which was reflected in his stats for the season as well, placing 15th and 10th in the league, respectively.</p>
            <p>Mohamed Salah (31), Willian (34), Tom Cairney (32), and Adam Lallana (35) are the remaining players that were predicted much higher than their given market values and for similar reasons to Pascal Groß and Thiago Silva... because they are "old". All of these players had very strong seasons (Mohamed Salah especially, 18 goals and 10 assists) and were extremely important to their teams. Despite this, their age causes them to be valued lower by the football community because once again, you're more likely to get injuried and you're past your prime (Mohamed Salah certainly isn't though).</p>
            <h3 className="red">Negatively Predicted Players</h3>
            <h4>Inflation in the market</h4>
            <p>There are a lot of players that got under predicted by their models by a large amount. A large group of them are defenders, that I believe the models incorrectly predicted. Ruben Diaz, Josko Gvardiol, Ben White, Gabriel M., Trent Alexander-Arnold, and some others are all some of the best defenders in the league and the model is predicting all of them to be much lower than their market value. The cause of this is inflation in prices of players.</p>
            <p>In the 2019/20 season only 18 defenders were thought to be worth 30 million euros or more. In the 2023/24 season that number has jumped to 40 defenders. Not to take anything away from the players because of how hard they worked to get where they are but the prices of some of these defenders are not justified. This leads to the top players being worth even more, which causes a big inflation in the average price for a top defender, such as the ones listed above. The models, not knowing this inflation has happened, predict that the defenders are worth what a top defender would be in previous seasons, not in the current economy, which is why a lot of defenders are being predicted incorrectly by around 30-35 million euros.</p>
            <h4>Insufficient playing time</h4>
            <p>Players such as Sandro Tonali, Christopher Nkunku, Ian Maatsen, Cheick Doucoure, and Reece James all were predicted extremely low values compared to their given market values. This is because these players played a few games (Less than 5 for most of them) throughout the season. Whether it was because they were banned from playing (Tonali for betting) or had injuries (Reece James, who has played in 52 of a possible 114 games through three seasons because of injury), these players did not have a significant enough amount of minutes for the models to get anywhere close to what their given market value is. But since the values should be based on how a player does throughout a season, I wouldn't necessarily consider these predictions to be incorrect. All of these players are relatively young and have a lot of potential to develop into great players, which is why their market values are set relatively high, but after a season of almost no game time, there is no way to tell if that is actually still the case.</p>
            <h4>Future Potential</h4>
            <p>The four players with the most difference in their given market values and predicted market values from the models are in their own group. These players are all young talents that are amazing players, and because of this they have high values based on how well they play, but they also are given an increased sum because they are still young and have the chance to develop into even better players. This is why their given market values exceed 100 million euros. Bukayo Saka, Phil Foden, and Erling Haaland are in the top 10 predicted market values throughout the entire dataset, so their great seasons were seen by the models and they were given very fair values.</p>
            <p>Declan Rice however, was predicted to have a value of 35 milion instead of 120 million euros. He was a top 15 player throughout the season in a few stats such as balls intercepted, progressive passes, tackles, touches on the ball, and combined for 15 goals and assists throughout the season. Funnily enough his team had a net 1.21 more goals per 90 minutes when he was off the field compared to when he was playing. Other than that, he had a good season, but nothing too spectacular, which I believe is why the model predicted 35 million, which is still a relatively decent number all things considered.</p>
            <h4>Players that actually had a poor season</h4>
            <p>Bruno Fernandes, Lucas Paqueta, Alexis Mac Allister, and Douglas Luiz are all very good players and for the most part deserve the market value they've been given. All of these players had a standout 22/23 season, which prompted them to have a high market value, but in the 23/24 season they didn't replicate nearly the same numbers as they did in the previous season. This should prompt their values to drop by some number. Bruno Fernandes' dropped by 5, Douglas Luiz' increased by 30, Mac Allister's increased by 5, and Paqueta's increased by 20. Despite the massive spikes in price for the two players, their statistics throughout the season were decent and better than most other players, but not nearly good enough to keep the values they garnered from the season before.</p>
            <h5>Rasmus Højlund</h5>
            <p>Rasmus at 20 years old was brought into the Premier Leauge as an exciting young player, even after having a mediocore previous season in Itay. And because of this excitement and buzz about how good of a player he could be come, his market value jumped by 20 million from the start of the 23/24 season to the end of the 23/24 season. However, he did not live up to his expectations at all. He scored 10 goals in 24 games, which is decent, but there were players who scored the same amount of goals in 10 games less and players that doubled his goal tally in the same amount of time as him. As a forward, scoring goals/helping your team score goals is the most important job, and he did not do that well enough, or much else that season, which is why the models predicted him at 17 million, a whopping 47.5 million less than his given market value.</p>
            <h5>Bernardo Silva</h5>
            <p>As much as I love Bernardo Silva, he isn't worth his 70 million euro market value anymore. He had a decent 23/24 season with 6 goals, tied for 12th in assists with 9, and 15th best in SCAs. But other than that, he did average compared to his midfield rivals. He recieved the ball in advanced positions 12th most in the leauge, but when he got them, most of the time he just passed the ball backwards and not much came of it which hurt statistics such as progressive passes. He's still a very good player and the model sees that by predicting him just shy of 37 million euros, about half of his given market value.</p>
            <h4>Unsure why the models predicted as they did</h4>
            <p>Mohammed Kudus came into the Premier League in the 23/24 season after transfering for 40 million euros. Looking at his statistics he had a very good debut season, which surprised me when the model predicted him at 9 million euros, when his given market value is 50 million. He is very good at taking on a player 1 on 1 and dribbling past them, utilizing his quick feet and speed. It shows too, because he attempted the most dribbles past a defender (221 times, second place was 169 times), and successfully got past the defender 124 of those times. He was in the top 20 for progressive passes received, times dribbled forward, GCAs, number of loose balls recovered, and tackles which one his team possession of the ball (2nd best for forwards). The rest of his stats, specifically passing, were not standout and below average for the most part, which is what the models seem to have picked up on, leading to his lower predicted value. He is the only player here where I would say the stats of the player do not agree with the output of the model (other than the inflation adjusted players).</p>
            <h2>Conclusion</h2>
            <p>After strenious analysis of the largest differences in market value and the models' predict values, I can definitely see where and why the model got certain outputs. Using Deep Learning this way, with this analysis, can lead football teams to start looking for possible undervalued players. By stripping away any biases that players could have and seeing how well they did based on statistics solely, teams can get a good starting point of which players they should look at getting. Then they can factor in their own biases, or other intangibles such as being injury prone, or not fitting the team dynamic.</p>
        </div>
        </>
    )
}

export default DLP1
